---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsysakura.
--- DateTime: 2025/3/24 9:37
---
if(redis.call('GETBIT', KEYS[1], ARGV[1]) == 1) then
    return "1"
end

local arr = redis.call('ZRANGEBYSCORE', KEYS[2], ARGV[1], ARGV[2], 'LIMIT', 0, 1)
if(#arr == 0) then
    return "2"
end

local cid = arr[1]
local _k1 = "prs:coupon:" .. cid
local _k2 = "prs:user:coupon:" .. cid

if(redis.call('EXISTS', _k1) == 0) then
    return "3"
end

-- 获取当前时间戳，转为毫秒
local currentTime = redis.call('time')
local currentTimestampMs = currentTime[1] * 1000 + math.floor(currentTime[2] / 1000)

-- 获取优惠券的 issueEndTime（假设是毫秒级时间戳）
local issueEndTime = tonumber(redis.call('HGET', _k1, 'issueEndTime'))

-- 比较时间戳
if(currentTimestampMs > issueEndTime) then
    return "4"
end

-- 用户限领次数比较
if(tonumber(redis.call('HGET', _k1, 'userLimit')) < redis.call('HINCRBY', _k2, ARGV[3], 1)) then
    return "5"
end

-- 设置 bit 标记为 1
redis.call('SETBIT', KEYS[1], ARGV[1], 1)

return cid
