---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsysakura.
--- DateTime: 2025/3/24 9:33
---
-- 优惠券 id
local cacheKey = KEYS[1]
-- 用户信息 key
local userKey = KEYS[2]
-- 用户 id
local userId = ARGV[1]
-- 当前的时间戳（秒 + 微秒）
local currentTime = redis.call('TIME')

-- 计算当前毫秒级时间戳
local currentTimestampMs = currentTime[1] * 1000 + math.floor(currentTime[2] / 1000)

-- 判断优惠券是否存在
if redis.call('EXISTS', cacheKey) == 0 then
    return 1
end

-- 判断库存是否大于 0
if tonumber(redis.call('HGET', cacheKey, 'totalNum')) <= 0 then
    return 2
end

-- 判断是否在发放期间
if tonumber(redis.call('HGET', cacheKey, 'issueEndTime')) < currentTimestampMs then
    return 3
end

-- 判断是否超出限领数量
local userReceiveCount = tonumber(redis.call('HGET', userKey, userId) or "0")
local userLimit = tonumber(redis.call('HGET', cacheKey, 'userLimit'))
if userReceiveCount >= userLimit then
    return 4
end

-- 扣减库存
redis.call('HINCRBY', cacheKey, 'totalNum', -1)

-- 增加用户领取记录
redis.call('HINCRBY', userKey, userId, 1)

-- 成功领取
return 0
